apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parquet-pvc
  namespace: weather-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: parquet-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/parquet-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parquet-consumer
  namespace: weather-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parquet-consumer
  template:
    metadata:
      labels:
        app: parquet-consumer
    spec:
      containers:
        - name: consumer
          image:  to-parquet:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: parquet-pvc